version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/counter
    overwrite: true
permissions:
  - object: /tmp/my-app
    owner: ec2-user
    mode: 464
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: ec2-user

