version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/counter
    overwrite: true
permissions:
  - object: /home/ec2-user/counter
    owner: ec2-user
    mode: 777
    type:
      - directory
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: ec2-user

