version: 0.0
os: linux
files:
  - source: scripts/server.js
    destination: /var/www/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 100
      runas: root

